### ISSUE TITLE
DBSessionRequest[_] in DBAction's apply(...) signature

### ISSUE THREAD

**Issue by azolotko** [playframework/play-slick#113]
Hi,

It is somewhat inconvenient that

```scala
def apply(requestHandler: DBSessionRequest[_] => SimpleResult)(implicit app: Application = null)
```

forces our handler to be agnostic regarding request body type, because sometimes we actually need the type to subtype a WrappedRequest[A]. 

Wouldn't it be better to define the bodyParser-less variant of ```apply(...)``` the same way as the ```transaction(...)``` analog is defined (at least for the sake of consistency)?

```scala
def transaction(requestHandler: DBSessionRequest[AnyContent] => SimpleResult)(implicit app: Application)
```

Thanks!

**Comment by dotta** [comment]
`DbSessionRequest` was removed from the latest play-slick release (i.e., v1.0.0). Hence, the reported problem does not exist anymore. See https://www.playframework.com/documentation/2.4.x/PlaySlickMigrationGuide#DBAction-and-DBSessionRequest-were-removed for details.
