### ISSUE TITLE
DDL Table Creation Problem

### ISSUE THREAD

**Issue by windweller** [playframework/play-slick#138]
I've been checking my ```1.sql``` file during starting phase, and this is my table generation sentence:

``` (Articles.ddl ++ Article_Labels.ddl ++ Labels.ddl ++ Messages.ddl ++ Users.ddl ++ S3Files.ddl).create``` (inside ```Global.scala``` file)

It turns out slick code generator is creating one table at a time. If that is the case, it's fine, but for some reason, it drops and creates table without any kind of rules.

I honestly don't know what's going on or what might cause the problem, but then i checked Slick's update and I saw this: "Code generator now generates an accumulated ddl value for all tables." I wonder if this is the cause. However, this fix is with Slick 2.0.1-RC1. Right now Play-Slick is based on Slick 2.0.0. How do I pull in 2.0.1 with my current Play-Slick? Is the code generator causing my problem?

**Comment by dotta** [comment]
We removed DDL generation in the last release of play-slick (v.1.0.0). See https://www.playframework.com/documentation/2.4.x/PlaySlickMigrationGuide#DDL-support-was-removed

I'm closing this ticket as it's no longer actual.
