### ISSUE TITLE
Need some documentation about Slick Enumeratos

### ISSUE THREAD

**Issue by loicdescotte** [playframework/play-slick#139]
The markdown documentation (avalaible here https://github.com/freekh/play-slick/tree/master/documentation)  needs to be updated before merging into Play core

**Comment by ms-tg** [comment]
@loicdescotte is this still needed? If so, where would I add the documentation?

**Comment by loicdescotte** [comment]
Hi,

I think it could be a good idea to add this kind of documentation here : https://github.com/playframework/play-slick/wiki/Usage

**Comment by dotta** [comment]
I'm closing this ticket as it's no longer actual.
