### ISSUE TITLE
multi table creation with the cake pattern

### ISSUE THREAD

**Issue by mekuriam** [playframework/play-slick#145]
I am facing an issue in which only the last component mixed into my DAO class is getting a create table query generated in evolutions' 1.sql.  I end up with the error [JdbcSQLException: Table "xxx" not found; for the rest.  

[JdbcSQLException: Table "xxx" not found;

https://groups.google.com/forum/#!topic/play-framework/ZEP7a-BdTU8

**Comment by dotta** [comment]
We removed DDL generation in the last release of play-slick (v.1.0.0). See https://www.playframework.com/documentation/2.4.x/PlaySlickMigrationGuide#DDL-support-was-removed

I'm closing this ticket as it's no longer actual.
