### ISSUE TITLE
BoneCP connection pool size

### ISSUE THREAD

**Issue by ploddi** [playframework/play-slick#193]
Seems like BoneCP connection pool size does not match thread pool size.

[BoneCP documentation](http://jolbox.com/index.html?page=http://jolbox.com/configuration.html) says that, for example, having 3 partitions and 5 max connection per partition will result in 15 open connections. But ```SlickExecutionContext.threadPoolExecutionContext(minConnections, maxConnections)``` will create pool of size 5.

**Comment by dotta** [comment]
The latest release of play-slick (v.1.0.0) delegates to Slick 3 the creation and management of the connection pool.  See https://www.playframework.com/documentation/2.4.x/PlaySlickAdvancedTopics#Connection-Pool for details.

I'm closing this ticket as it's no longer actual.
