### ISSUE TITLE
Document process for releasing play-slick

### ISSUE THREAD

**Issue by richdougherty** [playframework/play-slick#200]
Here's some draft docs, they still need to be checked when we do our next release. Some of this process could be automated.

http://notes.richdougherty.com/2014/08/publishing-play-slick-draft.html

Cc @pvlugter.

**Comment by dotta** [comment]
@richdougherty I believe this is no longer accurate. Can we close it?

**Comment by richdougherty** [comment]
You're right, my notes are probably not accurate any more. You're welcome to keep this ticket or close it depending whether you think it's worth documenting the release process for play-slick. I don't mind either way. :)

**Comment by dotta** [comment]
I'll cut 1.0.1 release and document the process. In theory, it should be as simple as calling a script with a few arguments.

**Comment by richdougherty** [comment]
Nice docs over in #295!
