### ISSUE TITLE
using different driver in cake pattern than db.default

### ISSUE THREAD

**Issue by ergomesh** [playframework/play-slick#212]
i have  many dbs with different drivers to connect to 

db.oracle. for example so I started working on the cake pattern

After reading 

https://github.com/playframework/play-slick/blob/master/samples/play-slick-cake-sample/app/models/DAO.scala

and 

https://github.com/playframework/play-slick/wiki/ScalaSlickDrivers

I setup the cake pattern for my other db.oracle where I'm stuck is loading the new driver in db.oracle.driver

I have tried
```
object current {
  val db = DB("oracle")
  val dao = new DAO(db.driver)      
} 
```

**You do not have an implicit Application in scope. If you want to bring the current running Application into context, just add import play.api.Play.current (adding that does not solve it)**
object current {
  val dao = new DAO(Config.driver)
}
```
object current {
 val dao = new DAO(Config.driver("oracle")) 
}
```
**missing arguments for method driver in trait Config;
follow this method with `_' if you want to treat it as a partially applied function**

this doesn't work in the DAO.scala file you get the error 

what I am really confused on is all of the sample code for using several databases and drivers actually never end up calling the different drivers

I have followed the sample to the T but still have no luck having it use the oracle connection

here is my application.conf specific it is starting the jdbc

```
db.default.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.default.url="jdbc:sqlserver:/xxx"
db.default.slickdriver=com.typesafe.slick.driver.ms.SQLServerDriver
db.default.user="xxx"
db.default.password="xxx"
slick.default="models.internal.*, models.security.*"

db.oracle.driver=oracle.jdbc.driver.OracleDriver
db.oracle.url="jdbc:oracle:xxx"
db.oracle.slickdriver=com.typesafe.slick.driver.oracle.OracleDriver;
db.oracle.user="xxx"
db.oracle.password="xxx"
slick.oracle="models.oracle.*"
```

**Comment by dotta** [comment]
@ergomesh The problem reported here is fixed in the last play-slick 1.0.0 release, as it uses stock Play 2.4 and Slick 3.0 (with no magic driver auto-detection logic). Please, read https://www.playframework.com/documentation/2.4.x/PlaySlickMigrationGuide and upgrade to play-slick 1.0.0.
