### ISSUE TITLE
Version for slick 3.0-M1

### ISSUE THREAD

**Issue by bambuchaAdm** [playframework/play-slick#225]
I there any problem to release play-slick for slick-3.0-M1 ? I would be very helpful for library build on top play-slick.

**Comment by jvican** [comment]
It would be great to have play-slick working with 3.0-M1 as they have introduced asynchronous actions and reactive streams to deal with the data.
Any expected date to be released guys?
Thank you

**Comment by dotta** [comment]
play-slick 1.0.0 was released and it supports Slick 3.0. Hence, I'm closing this ticket.
