### ISSUE TITLE
Documentation missing for maxQueriesPerRequest

### ISSUE THREAD

**Issue by studiodev** [playframework/play-slick#229]
Hello,

Play-slick use a `maxQueriesPerRequest` property to check if the DB is available.
Nothing is explained about this property, especially if we need to tweak this value and how.

A little explanation about this property would make it more comprehensible.

**Comment by dotta** [comment]
`maxQueriesPerRequest` configuration was removed in play-slick 1.0.0. Read https://www.playframework.com/documentation/2.4.x/PlaySlickMigrationGuide#Thread-Pool for details.
