### ISSUE TITLE
Support for Slick 3.0

### ISSUE THREAD

**Issue by vrcod** [playframework/play-slick#231]
Slick 3.0-RC1 was released. Are you guys planning a version of play-slick supporting it?

**Comment by jvican** [comment]
Is there any way we can help to release it?

**Comment by diwalak** [comment]
+1. Can we please have support for 3.0-RC1 considering that it is a very major break

**Comment by soc** [comment]
Would be interested in this, too.

**Comment by richdougherty** [comment]
@dotta is working on this now. :)

**Comment by dborovikov** [comment]
+1. I have prod issue with big result sets, but settings like fetchSize can be controlled only in Slick 3.0.

**Comment by anand-singh** [comment]
+1 I have started a application in slick and play

**Comment by stusmall** [comment]
What versions of play will it support?

**Comment by dotta** [comment]
@stusmall Likely Play 2.4.

**Comment by vrcod** [comment]
@dotta Slick 3 RC2 was released, so it looks that Slick 3 will be released before Play 2.4, would you consider making it Play 2.3 compatible in such case?

**Comment by dotta** [comment]
@vrcod I'll keep this in mind, but no guarantees for the moment.

**Comment by vrcod** [comment]
Slick 3 RC3 is out and Play 2.4-RC1 is out now too, any idea on ETA of play-slick support for these?

**Comment by dotta** [comment]
ETA: I'd like to publish a release (0.9.0-M5?) as soon as the related PR is merged https://github.com/playframework/play-slick/pull/239

Current support is for Play 2.4 and Slick 3 (no plan at the moment for older Play releases, but I'm happy to discuss things if anyone is interesting on contributing it).

**Comment by diwalak** [comment]
Great job !!
How do i access the documentation ? The wiki seems not to be updated.

**Comment by jroper** [comment]
Which wiki?  Docs get deployed nightly to playframework.com, though that's currently broken due to us being in the middle of a migration to change which snapshot repositories we use.

**Comment by adamkuipers** [comment]
Here's probably talking about the project wiki, https://github.com/playframework/play-slick/wiki

**Comment by jroper** [comment]
Right.  We can probably turn that off once Play 2.4 is released, since the we know aggregate the play-slick docs into Play 2.4.  We don't maintain the wiki at all, all the docs for play-slick now are in the play-slick repo itself.

**Comment by vrcod** [comment]
Just an update - Slick 3.0 is now released.

**Comment by dotta** [comment]
@vrcod Yep, and play-slick was also updated https://github.com/playframework/play-slick/commit/2806b1a52f3c39d39350f482c8e3949e9963f3b5 ;-)

We will have a 1.0.0-RC1 release soon.
