### ISSUE TITLE
Add datasource to Table mapping

### ISSUE THREAD

**Issue by phucnh** [playframework/play-slick#235]
I want to JOIN tables at different database and I follow this topic: http://stackoverflow.com/questions/21603506/how-can-i-join-tables-in-different-databases-on-the-same-server-using-slick
So i can define like
```scala
class SomeTable(tag: Tag) extends Table[(Int,String)](
  tag, Some("SOME_DB"), "SOME_TABLE"
) {
  def id = column[Int]("id")
  def title = column[String]("title")
  def * = (id, title)
}
```
Which "SOME_DB" is the real schema name. But Play use datasource (has been define in ```application.conf```) for manage database connection. So, i think if can specify the datasource when define database will be better.
For example
```
db.web.driver=com.mysql.jdbc.Driver
db.web.url="jdbc:mysql://localhost/some_db"
```

```scala
class SomeTable(tag: Tag) extends Table[(Int, String)](tag, Some("web"), "SOME_TABLE") {
```

**Comment by dotta** [comment]
@phucnh I'm not following what is that would need to be changed in play-slick to support this. Could you elaborate more on what we would need to change in play-slick 1.0 to support this.

**Comment by dotta** [comment]
Please, reopen if you can provide more details.
