### ISSUE TITLE
Generated DDL could include the dialect/driver in comments

### ISSUE THREAD

**Issue by slorber** [playframework/play-slick#236]
This can be useful in case you are using different driver per env to debug more easily.

In my case we use an embedded H2 DB in dev and MySQL in integration/production. I had deployment bugs because of trying to apply H2 DDL to a MySQL DB

**Comment by dotta** [comment]
We removed DDL generation in the last release of play-slick (v.1.0.0). See https://www.playframework.com/documentation/2.4.x/PlaySlickMigrationGuide#DDL-support-was-removed

I'm closing this ticket as it's no longer actual.
