### ISSUE TITLE
Add configuration to allow DDL generation in production mode

### ISSUE THREAD

**Issue by slorber** [playframework/play-slick#237]
We are using H2 in DEV and MySQL in staging/production. 
This is temporary and won't always be the case, as we are still building the application. Our production is instable and the schema is evolving, but we have to show progress to a customer. It is more like a "demo production"

We use "run" in dev and that generates H2 DDL that we keep out of SCM for now.
We use "start" in prod and that does not generate MySQL DDL as saw in the source code: https://github.com/playframework/play-slick/blob/56b72cb9f2d2d6204a1d8eaa723bf51d635152f7/src/main/scala/play/api/db/slick/SlickModule.scala#L41

It would be nice to be able to enable or disable DDL generation in our own, so that I could use PROD mode, generate MySQL DDL and make our demo server update itself automatically (we don't care yet about loosing data)

**Comment by dotta** [comment]
We removed DDL generation in the last release of play-slick (v.1.0.0). See https://www.playframework.com/documentation/2.4.x/PlaySlickMigrationGuide#DDL-support-was-removed

I'm closing this ticket as it's no longer actual.
