### ISSUE TITLE
Documentation shows 1.0.0-RC1 is current version

### ISSUE THREAD

**Issue by stusmall** [playframework/play-slick#244]
The documentation shows that the most current release is 1.0.0-RC1.  I can't find anywhere where this has been released.  sbt can't resolve it.  Looking at mvnrepository.com, the newest I see is 0.9.0-M4.

Has the documentation been updated too soon or am I missing something in my sbt set up?

**Comment by dumb-questions** [comment]
I have the same problem, but found a solution (other than to compile it myself). See my edit here: https://github.com/playframework/play-slick/pull/239#issuecomment-98371315

**Comment by stusmall** [comment]
It resolved last night when I tried it.  Thanks.
