### ISSUE TITLE
Don't use play.modules.disabled

### ISSUE THREAD

**Issue by jroper** [playframework/play-slick#245]
`play.modules.disabled` is intended for end users to be able to override what modules are enabled by default. If libraries provide config for it, this undermines what the user can do - for example, if the user for whatever reason has play-slick on the classpath, but they want it disabled and Play's built in DBModule enabled, then they can't do that, because slick has already provided default configuration that disables Play's built in DBModule.

Additionally, since Play by default provides an empty list for the disabled modules, this means the current configuration is susceptible to classpath ordering issues, if Play's jar is loaded after play-slick, then play-slicks disabled modules config will be overridden by the empty list that Play provides.

**Comment by jroper** [comment]
A few possible solutions here:

* Require users to explicitly disable Play's built in DbApi module and enable slicks.
* Separate Play's DbApi and the evolutions plugin out from the implementation, that way, only one of slick and play-jdbc will be on the classpath, and both of them can provide bindings by default, with the user having to disable one if they include both.
* Rather than having a separate implementation of `DbApi` and separate configuration namespace, reuse Play's, but implement Play's `play.api.db.ConnectionPool` trait using Slick - thus Slick implements and manages the connection pool.  Users will have to manually specific the slick connection pool for each datasource.

**Comment by dotta** [comment]
> Require users to explicitly disable Play's built in DbApi module and enable slicks.

While I don't particularly like this solution, this was easy to implement, and [here](https://github.com/dotta/play-slick/commit/aa182e7989f9354fbf1f7f80257de46a55342829) is a link to the commit.

> Separate Play's DbApi and the evolutions plugin out from the implementation, that way, only one of slick and play-jdbc will be on the classpath, and both of them can provide bindings by default, with the user having to disable one if they include both.

I like this solution. I thought it was too late for doing such a change in Play 2.4. Looks like I'm not, so I'll have a look at this right away.
