### ISSUE TITLE
Docs missing for ddl plugin/evolutions config

### ISSUE THREAD

**Issue by onelson** [playframework/play-slick#261]
Previously, we'd set `slick.default="dotted.path.to.search.*"` in our application.conf to tell the ddl plugin which which classes to watch for changes, and output new sql for evolutions, but this doesn't seem to work any more.

Went poking around the source to try and find the new settings key, but came up empty. Regardless, I guess the docs need updating.

**Comment by onelson** [comment]
Oh boy... I'm a dummy. Apparently the DDL plugin was deprecated (noted at the bottom of https://www.playframework.com/documentation/2.4.x/PlaySlickMigrationGuide). Understandable change, I just missed this tidbit in the docs on my first 8 times through.

I might recommend adding a note about the old `slick.defaults` config key being ignored under the Database Configuration section (even though this is not strictly the same topic), and potentially link to the bottom of the page with a named anchor.

**Comment by dotta** [comment]
@onelson Hey, sorry I've seen this ticket only now. I don't mind having an additional note about it, feel free to create a PR (alternatively, this could also be checked when starting the play-slick module, and a warning could be issued to the user. Up to you!).
