### ISSUE TITLE
Applying evolutions leaves old connections open

### ISSUE THREAD

**Issue by zlangbert** [playframework/play-slick#263]
I'm running an app in dev mode and connecting to a local postgres server. Every time an evolution is applied it seems to open a new set of connections without closing the old ones. After changing an evolution script a few times I hit the postgres server connection limit and it started throwing exceptions. This is using Play 2.4-RC5, Slick 3, play-slick 1.0.0-RC3 and HikariCP 2.37.

**Comment by dotta** [comment]
Fixed by https://github.com/playframework/play-slick/pull/291
