### ISSUE TITLE
di-sample per request create new  Application,CatDAO

### ISSUE THREAD

**Issue by evandu** [playframework/play-slick#268]
I run di-sample example, i find per request  new  Application,CatDAO,DogDAO why?
I have to add @Singleton ..

**Comment by iref** [comment]
I think this is default behaviour of Guice injector, which is default implementation of DI in Play 2.4.
You can find more details in [Guice documentation](https://github.com/google/guice/wiki/Scopes).

**Comment by julienrf** [comment]
It should not be the case when you use an “injected” router (which is the case in the sample)

**Comment by iref** [comment]
Oh, I didn't know that. Thanks for clarification, @julienrf.
