### ISSUE TITLE
Should I use slick.driver.<driver>.api._ import?

### ISSUE THREAD

**Issue by sedovalx** [playframework/play-slick#277]
After migrating to PlaySlick 1.0.0 there is no way to use generic `import play.api.db.slick.Config.driver.simple._`. So in may case `import slick.driver.PostgresqlDriver.api._` spreads all over the code. Is it recomended way? But what if I need to switch the database provider? Should I not only change config but replace the imports in code?

**Comment by dotta** [comment]
@sedovalx Please, next time ask this kind of questions in the [playframework-user ML](https://groups.google.com/forum/#!forum/play-framework). 

> After migrating to PlaySlick 1.0.0 there is no way to use generic import play.api.db.slick.Config.driver.simple._.

That functionality was removed. Read the Play Slick 1.0 migration doc https://www.playframework.com/documentation/2.4.x/PlaySlickMigrationGuide#Automatic-Slick-driver-detection for understanding the rationale and learn how driver should be imported.

> So in may case import slick.driver.PostgresqlDriver.api._ spreads all over the code. Is it recomended way?

Definitely not. Please, read the Play Slick documentation https://www.playframework.com/documentation/2.4.x/PlaySlick, and if you have questions feel free to ask them in the [playframework-user ML](https://groups.google.com/forum/#!forum/play-framework).
