### ISSUE TITLE
Example play-slick project

### ISSUE THREAD

**Issue by wsargent** [playframework/play-slick#278]
This is an example project of Play 2.4 with Slick 3.0, using HikariCP and Postgresql, but not using play-slick.  Could be useful for documentation, so making a note.

https://github.com/wsargent/play-slick-3.0/

**Comment by huntc** [comment]
We have one here also: https://github.com/typesafehub/customers

Markus and I developed it during the code retreat, and then Ed and I presented it at ScalaDays. It is being revolved a little further and in going to provide a tutorial for it.

**Comment by huntc** [comment]
We use play-slick also. :-)

**Comment by mariobriggs** [comment]
I have been trying to get Play 2.4.2 working on IBM Bluemix/CloudFoundry using the spring-cloud-connectors and specifying variables like [${?cloud.services.tasks-db.connection.uri}](https://github.com/cloudfoundry-samples/zentasks-scala-cloudfoundry/blob/master/conf/application.conf), but those don't work in 2.4.2. Those env vars dont get resolved and they do in 2.3.9. @huntc i see you are doing some Dynamic Datasource in the sample you provided... is there some trick for env vars too ?

**Comment by bravegag** [comment]
Ohhh finally an example that works and can be reused. I have been trying to adopt Play-Slick for two days now without success. The examples are not easy to use as template due to the complex setup whereas that example is perfect even though it doesn't use Play-Slick!!

**Comment by pedrorijo91** [comment]
also, a tutorial example: [https://pedrorijo91.github.io/blog/play-slick/](https://pedrorijo91.github.io/blog/play-slick/) and code at Github under [https://github.com/pedrorijo91/play-slick3-steps](https://github.com/pedrorijo91/play-slick3-steps)

**Comment by wsargent** [comment]
There's also examples in playframework: https://playframework.com/download

**Comment by wsargent** [comment]
I think this can be closed at this point.
