### ISSUE TITLE
play-slick-evolutions_2.11;0.8.0 not found

### ISSUE THREAD

**Issue by mfirry** [playframework/play-slick#282]
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play#play-slick-evolutions_2.11;0.8.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

I can't even find it on Maven Central.

**Comment by marcospereira** [comment]
Hello @mfirry,

`play-slick-evolutions` is available only in play-slick 1.0.0+.
