### ISSUE TITLE
Release play-slick 1.1.0-M1 (supporting Slick 3.1.0-M1)

### ISSUE THREAD

**Issue by dotta** [playframework/play-slick#286]
Slick 3.1.0-M1 was recently released, and I've created a branch to release play-slick against it (see https://github.com/playframework/play-slick/tree/1.1.x).

When releasing it, make sure to create a tag named 1.1.0-M1 (this is because we want to reserve 1.0.x stream for releasing play-slick against Slick 3.0.x).

**Comment by enragedginger** [comment]
+1

**Comment by dotta** [comment]
We will do it, but it may take a week or so before we get to it. In the meanwhile, you can do a local publish of [this branch](https://github.com/playframework/play-slick/tree/1.1.x).

**Comment by rdsubhas** [comment]
+1, thanks

**Comment by jroper** [comment]
@dotta do you have access to vegemite yet?  For future reference, you can perform the release yourself by sshing into vegemite, switching to the play account, and running:

    ./release --project play-slick --branch 1.1.x

from the `deploy` directory.

**Comment by jroper** [comment]
1.1.0-M1 is released.

**Comment by dotta** [comment]
Thanks James!

**Comment by dotta** [comment]
See

* https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/play-slick_2.10/1.1.0-M1/
* https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/play-slick-evolutions_2.10/1.1.0-M1/
* https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/play-slick_2.11/1.1.0-M1/
* https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/play-slick-evolutions_2.11/1.1.0-M1/
