### ISSUE TITLE
Compile-time DI suppport ?

### ISSUE THREAD

**Issue by NicolaeNMV** [playframework/play-slick#307]
Hi, at this moment I can't find any example of Compile-time DI with play slick. Do you have any ?

I think it would be extremely useful to have an example like this one for runtime DI https://github.com/playframework/play-slick/tree/master/samples/di

Thanks

**Comment by cchantep** [comment]
Hi, please either ask questions on the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework), or directly create there a PR with appropriate doc changes. Best regards.
