### ISSUE TITLE
Missing standalone and plain SQL examples

### ISSUE THREAD

**Issue by bravegag** [playframework/play-slick#316]
The samples provided are a bit difficult to reuse as template for a new or an existing project because it is not obvious how to get all the dependencies right. It would be most helpful having a really standalone sample where Play and Slick dependencies are clear in build.sbt and not as part of a complex multi-module project. Ideally the dependencies should be close to what activator new Play application generates because unless you are a `sbt` guru it is not trivial to work out the exact same dependency soup. For instance, my current `build.sbt` looks like this and it is a slightly customized version of the Play 2.4.3 new app generated with activator but I get missing dependencies that are otherwise available in your examples:

```
name := """test-app"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).
  enablePlugins(PlayScala).
  enablePlugins(BuildInfoPlugin).
  settings(
    buildInfoKeys := Seq[BuildInfoKey](name, version, scalaVersion, sbtVersion),
    buildInfoPackage := "buildinfo"
  ) 

scalaVersion := "2.11.6"

libraryDependencies ++= Seq(
  "com.typesafe.slick" %% "slick" % "3.0.3",
  "com.typesafe.slick" %% "slick-codegen" % "3.0.3",
  "org.postgresql" %  "postgresql" % "9.4-1201-jdbc41",
  "com.typesafe.play" %% "play-jdbc-api" % "2.4.3",
  "com.typesafe.play" %% "play-slick" % "1.0.1",
  "com.typesafe.play" %% "play-slick-evolutions" % "1.0.1",
  jdbc,
  cache,
  ws,
  specs2 % Test
)

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"

// Play provides two styles of routers, one expects its actions to be injected, the
// other, legacy style, accesses its actions statically.
routesGenerator := InjectedRoutesGenerator
```

I could also not find any DAO examples using the Plain SQL approach, I prefer to implement my DAOs mostly with SQL prepared statements on top of Slick code generated models and use Slick only where it can be elegantly reused. For example in an older Slick Play version I had:

```
  /**
   * Returns all the accounts.
   *
   * @return all the accounts.
   */
  def findAll(): List[AccountRow] = DB.withDynSession {
    Q.queryNA[AccountRow](
        s"""select * 
            from "${Account.baseTableRow.tableName}"
            where "deleted" is null
            order by "account_name"""").list
  }
```

I have no idea how to replicate such implementation using play-slick and using the latest versions of everything as so much has changed.

**Comment by pedrorijo91** [comment]
+1

**Comment by pedrorijo91** [comment]
also, a tutorial example: [https://pedrorijo91.github.io/blog/play-slick/](https://pedrorijo91.github.io/blog/play-slick/) and code at Github under [https://github.com/pedrorijo91/play-slick3-steps](https://github.com/pedrorijo91/play-slick3-steps)

**Comment by marcospereira** [comment]
Hey @bravegag and @pedrorijo91, does this projects helps?

https://github.com/playframework/play-isolated-slick

If so, I think we can close this issue.
