### ISSUE TITLE
Error: no configuration setting found for key db

### ISSUE THREAD

**Issue by bravegag** [playframework/play-slick#317]
I get the following error when I configure my application.conf to have `slick.dbs.default.*` keys rather than  the standard play `db.default.*` :

		! @6nj4dj3a0 - Internal server error, for (GET) [/] ->
		 
		play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector, see the following errors:

		1) Error in custom provider, com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'db'
		  while locating play.api.db.evolutions.ApplicationEvolutionsProvider
		  at play.api.db.evolutions.EvolutionsModule.bindings(EvolutionsModule.scala:22):
		Binding(class play.api.db.evolutions.ApplicationEvolutions to ProviderConstructionTarget(class play.api.db.evolutions.ApplicationEvolutionsProvider) eagerly) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
		  while locating play.api.db.evolutions.ApplicationEvolutions

My build.sbt looks like this:

	name := """testapp"""

	version := "1.0-SNAPSHOT"

	lazy val root = (project in file(".")).
		enablePlugins(PlayScala).
		enablePlugins(BuildInfoPlugin).
		settings(
		  buildInfoKeys := Seq[BuildInfoKey](name, version, scalaVersion, sbtVersion),
		  buildInfoPackage := "buildinfo"
		)	

	scalaVersion := "2.11.6"

	libraryDependencies ++= Seq(
	  "org.postgresql" % "postgresql" % "9.4-1201-jdbc41",
	  "com.typesafe.play" %% "play-slick" % "1.0.1",
	  "com.typesafe.play" %% "play-slick-evolutions" % "1.0.1",
	  "com.typesafe.slick" %% "slick-codegen" % "3.0.3",
	  cache,
	  ws,
	  specs2 % Test
	)

	resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"

	// Play provides two styles of routers, one expects its actions to be injected, the
	// other, legacy style, accesses its actions statically.
	routesGenerator := InjectedRoutesGenerator

**Comment by dotta** [comment]
@bravegag Hi! Please, use the [playframework mailing list] for usage questions about play-slick.
