### ISSUE TITLE
SQLTimeoutException: Timeout after 1000ms of waiting for a connection.

### ISSUE THREAD

**Issue by xring** [playframework/play-slick#320]
Hi:

I'm using play-slick with slick 3.0.0 in this way:

I got a connection by 
```scala
val conn = db.createSession.conn
```
then got statement:
```scala
val statement = conn.prepareStatement(querySQL)
```
and return ResultSet:
```scala
Future{statement.executeQuery()}
```

But I got a problem: I tried to use this query about 50 times, then, I got the exception:
> SQLTimeoutException: Timeout after 1000ms of waiting for a connection.

I know this may caused by connections are not closed and  **I didn't close the connection or session in my code manually.**

I want to know:

- Will connection create by my way close and return to connection pool automatically?
- Was my situation caused by connection didn't release?
- How to close a connection manually?

Any help would be greatly appreciated!

**Comment by dotta** [comment]
@xring Hi. The issue tracker is not the right place for usage questions, please use the [playframework](https://groups.google.com/forum/#!forum/play-framework) or the [Slick](https://groups.google.com/forum/#!forum/scalaquery) mailing list (the latter seem more appropriate for your question).
