### ISSUE TITLE
Release play-slick 1.1.0 final with Slick 3.1.0 final

### ISSUE THREAD

**Issue by dotta** [playframework/play-slick#321]

**Comment by dotta** [comment]
https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/play-slick_2.10/1.1.0/
https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/play-slick-evolutions_2.10/1.1.0/
https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/play-slick_2.11/1.1.0/
https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/play-slick-evolutions_2.11/1.1.0/

**Comment by misto** [comment]
:+1:
