### ISSUE TITLE
Tests for composable methods

### ISSUE THREAD

**Issue by nemoo** [playframework/play-slick#343]
Hi!

I find that in real world projects you often need to carry out multiple interactions with a database within one transaction.

Therefore, my daos almost exclusively look like this. They return DBIO to be composable: 
  def findById(id: Long): DBIO[Option[Project]] =
    Projects.filter(_.id === id).result.headOption

When  i look at the ModelSpec tests of the computer-database sample, they support this different style: 
  def findById(id: Long): Future[Option[Computer]] =
    db.run(computers.filter(_.id === id).result.headOption)

and look like this:

```
"be retrieved by id" in new WithApplication {
  val macintosh = Await.result(computersDao.findById(21), Duration.Inf).get
  macintosh.name must equalTo("Macintosh")
  macintosh.introduced must beSome.which(dateIs(_, "1984-01-24"))
}
```

My question:
How would an equivalent test look like for the style that returns a DBIO instead of a Future?

I could not find any fitting examples anywhere on the whole internet :)

Thanks!

**Comment by schmitch** [comment]
you could do two things, either check the generated statement / ast.
So if you have `computersDao.findById(21)` which will be a `DBIO[Option[Int]]` you could do the following:

    def findById(id: Int): DBIO[Option[Int]] = {
    sql"SELECT * FROM bla WHERE id = $id".as[Int].headOption
    }
    // Test code:
    findById(1).statements.head must equalTo("SELECT * FROM bla WHERE id = ?")

Or you could easily write a wrapper around Await.result and db.run:

    trait DBIOTest {
        protected object driver extends slick.driver.PostgresDriver

        import driver.api._

        def await[T](f: Future[T]): T = Await.result(f, Duration.create(5, TimeUnit.MINUTES))

        def run[R](body: DBIOAction[R, NoStream, Nothing])(implicit app: Application) = {
            val dbConfigProvider = app.injector.instanceOf[DatabaseConfigProvider]
            val dbConfig = dbConfigProvider.get[PostgresDriver]
            val db = dbConfig.db

            db.run(body)
        }
    }

    // Now you could run your code via:
    val dbio: DBIO[Opton[Int]] = findByUserId(1)
    val awaited = await(run(dbio))

**Comment by nemoo** [comment]
Your second suggestion looks very nice to me. Thanks a lot!
