### ISSUE TITLE
Monitor pool performance with metrics, How to set up poolName not use 'default'

### ISSUE THREAD

**Issue by ans76** [playframework/play-slick#344]
I integrate metrics and play, attemp to monitor pool performance, dose play-slick plugin offering configuration with that? and how to register MBeans to play environment.

I find one setting like "registerMbeans=true" in play older version, but I have no idea with play 2.4

@dotta

**Comment by marcospereira** [comment]
See the docs here (make sure to expand the forConfig row in the doc):

http://slick.lightbend.com/doc/3.2.0-RC1/api/index.html#slick.jdbc.JdbcBackend$DatabaseFactoryDef@forConfig(String,Config,Driver,ClassLoader):Database

There is still a `registerMbeans` property that you can configure. Closing this issue.
