### ISSUE TITLE
Can't inject slick dao in an Actor

### ISSUE THREAD

**Issue by pangwa** [playframework/play-slick#352]
DatabaseConfigProvider requires a play application to get the db configurations. Actors are initialized before application start and the Play.current isn't ready at that time. Below code will not work in play because it can't create MyDAO while initializing MyActor before application start. 
E.g. 
```
class MyDAO @Inject()() extends HasDatabaseConfig[JdbcProfile] {
  protected val dbConfig = DatabaseConfigProvider.get[JdbcProfile](Play.current);
}

class MyActor @Inject() (myDAO: MyDAO) extends Actor{
}
```

How to workaround this issue?

**Comment by wsargent** [comment]
Does this work?

```
class MyDAO @Inject()(val dbConfig: DatabaseConfig) extends HasDatabaseConfig[JdbcProfile] {
   
}
```

**Comment by pangwa** [comment]
It works, Thanks very much!

I created the actors by adding an actor module in the application.conf:

play.modules.enabled += "actors.ActorModule" 

It looks like actors are crated before the  application start in this way.
