### ISSUE TITLE
Play 2.5 + Slick + DI Issue

### ISSUE THREAD

**Issue by cokleisli** [playframework/play-slick#361]
I have DAO defined as follows:

    @Singleton
    class MyDAO @Inject()(protected val dbConfigProvider: DatabaseConfigProvider) extends HasDatabaseConfigProvider[JdbcProfile]  {

I have an integration test which references this DAO:

    class SomeIntegrationTest {
    
      lazy val someVal = new MyDAO

How can I inject the DatabaseConfigProvider into the MyDAO in the SomeIntegrationTest? I cannot inject one in the constructor of the test because test classes do not take constructor parameters.

**Comment by marcospereira** [comment]
Hello @cokleisli, could you please use the [mailing list](https://groups.google.com/forum/#!forum/scalaquery) to get help? The issue tracker is used only to report bugs and issues.

Thanks.
