### ISSUE TITLE
Disable play-slick when running unit tests

### ISSUE THREAD

**Issue by dev-tim** [playframework/play-slick#366]
Hello! I have following issue, not sure that it's just play-slick, but could be. 

I have a Play 2.4 (Scala) application that uses Slick 3 and play-slick in particular, to communicate with the database. Also I use Guice DI . 

Everything works fine, but I can't run unit tests with no database if I need to create a fake application instance to test some services. I tried to disable play-slick and play-flyway modules but database connection still try to init upon unit test run. 

How would I disable play-slick else, if I miss something? 

Here is a sample code for fake application init:  

```scala
implicit var application: Application = new GuiceApplicationBuilder()
    .in(Mode.Test)
    .global(new FakeGlobal).overrides(new ScalaModule {
    override def configure(): Unit = {
      bind[SomeDao].toInstance(mock[SomeDao])
      bind[SomeService].toInstance(mock[SomeService])
      .... // some other services
    }
  }).configure("db.default.migration.auto" -> false)
    .configure("db.default.migration.initOnMigrate" -> false)
    .configure("play.modules.disabled" -> List("org.flywaydb.play.PlayModule", "play.api.db.slick.SlickModule")).build()
```

Thanks in advance, will appreciate any help!

**Comment by marcospereira** [comment]
Hello @dev-tim,

The [mailing list](http://groups.google.com/group/scalaquery) would be a better place to discuss this. Github issues are for reporting bugs and feature, not for general discussion and getting help. You can see other community channels here:

http://slick.typesafe.com/community/

**Comment by norcalli** [comment]
This question never appears in the slick mailing list, I don't think it's productive to turn him away because the mailing list is not as user friendly or even SEO friendly. I have the exact same problem as the original poster and no resolution.

**Comment by JakubKahovec** [comment]
I had the same issue and resolved it by disabling connection pooling to my db resources

`override def fakeApplication(): Application = new GuiceApplicationBuilder().configure(Map("slick.dbs.mydbresource.db.connectionPool " -> "disabled")).build()`
