### ISSUE TITLE
Can't create function in play-slick evolution

### ISSUE THREAD

**Issue by steve-ng** [playframework/play-slick#367]
Below is the function I am creating in play-slick

```
CREATE OR REPLACE FUNCTION update_changetimestamp_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.changetimestamp = now();
   RETURN NEW;
END;
$$ language 'plpgsql';
```

The above function runs perfectly on postgres console, however when I run it from evolution, it gives the following error

> We got the following error: ERROR: unterminated dollar-quoted string at or near "$$ BEGIN NEW.changetimestamp = now()" Position: 79 [ERROR:0, SQLSTATE:42601], while trying to run this SQL script:

Any idea what's going on?

**Comment by lbialy** [comment]
I had similar problem and solution was related to how evolutions are parsed and escaped. Problem was solved by duplicating every semicolon between $$ symbols - in your case now();; NEW;; and END;;

**Comment by schmitch** [comment]
Actually this is not a Bug, it's actually documented here: https://www.playframework.com/documentation/2.5.x/Evolutions#Evolutions-scripts in the orange box.

**Comment by Vitucho** [comment]
well is not a bug, but is dificult to figure it out! Thanks
