### ISSUE TITLE
java.util.concurrent.RejectedExecutionException in specs

### ISSUE THREAD

**Issue by dsounded** [playframework/play-slick#369]
I use Scala/Play/Slick for my app. When I run solo test it works good, but when I try to run 2 or more specs at the same time, all the specs after first one fail with:

`java.util.concurrent.RejectedExecutionException: Task slick.backend.DatabaseComponent$DatabaseDef$$anon$2@26f33de8 rejected from java.util.concurrent.ThreadPoolExecutor@7802c94b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]`

Any suggestions ?

ScalaTest:

`import org.scalatestplus.play._`

`class SomeSpec extends PlaySpec with OneAppPerTest {`

**Comment by dsounded** [comment]
OneAppPerTest -> OneAppPerSuite solves the problem, but i think this should be fixed anyway

**Comment by wsargent** [comment]
Hi @dsounded the bug tracker is for tracking bugs in Play itself -- please bring up any problems in applications on the mailing list @ https://groups.google.com/forum/#!forum/play-framework

**Comment by dsounded** [comment]
@wsargent  Play comes with default specs, they use `OneAppPerTest`, basically you can include `play-slick` and have that error, isn't this a bug ?

**Comment by gmethvin** [comment]
@dsounded Without seeing your tests it's hard to know if it's a bug in play-slick, scalatestplus-play, Play itself, or in your code/tests.

It's going to be much more useful to you and the Play community to have a discussion on the mailing list rather than this issue tracker, since few people are monitoring the issues here.

**Comment by dsounded** [comment]
@gmethvin thanks for the response, OneAppPerSuite works only for 1 suite, if I have another - it will fail, basically I thinks that's a problem of `scalatestplus`, but anyway I decided not to use OneAppPerSuite nor OneAppPerTest
