### ISSUE TITLE
Use Slick in Play Java project

### ISSUE THREAD

**Issue by shayhz** [playframework/play-slick#372]
Hi,

I've a Play project written in Java.
Can I use Slick with Java (I used it in the past with Scala and it was great!)?

10x,

**Comment by schmitch** [comment]
this is a issue tracker and not a generel question board, please feel free to ask your question on a mailing list.

Also, this is just a project that helps integrating slick with play! and I'm also pretty sure that you can't use slick with java (actually some things might work).
