### ISSUE TITLE
Scala 2.12 version solicited!

### ISSUE THREAD

**Issue by Unmoving** [playframework/play-slick#373]

**Comment by djx314** [comment]
I saw play-slick 3.0.0-M1 with play 2.6.0-M1(already build with 2.12), but play-slick 3.0.0-M1 do not confirm with scala 2.12, any update?

**Comment by marcospereira** [comment]
We now have a 3.0.0-M2 version built with Scala 2.12:

https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/play-slick_2.12/3.0.0-M2/

Closing this issue.
