### ISSUE TITLE
SlickComponents.api is unclear

### ISSUE THREAD

**Issue by danielnixon** [playframework/play-slick#382]
`play-slick` provides a `SlickComponents` trait for compile-time dependency injection, in the style of `I18nComponents`, `EvolutionsComponents`, etc.

The problem is that its `api` property becomes ambiguous/unclear when you've mixed in a bunch of other `*Components`. The other `*Components` are better in this regard, with properties like `messagesApi`, `defaultCacheApi`, `dbApi`, etc.

It might be worthwhile to deprecate `SlickComponents.api` in favour of a new `SlickComponents.slickApi` or something like that.

**Comment by marcospereira** [comment]
@danielnixon that makes sense to me.

Do you want to submit a pull request to fix this?

Thanks!
