### ISSUE TITLE
Evolutions not applied on play 2.5.5 and above

### ISSUE THREAD

**Issue by emsoft** [playframework/play-slick#383]
When use h2 inmemory DB with following configurations:

# application.conf
```
slick.dbs.default.driver="slick.driver.H2Driver$"
slick.dbs.default.db.driver="org.h2.Driver"
slick.dbs.default.db.url="jdbc:h2:mem:playSlick"

play.evolutions {
  autoApply = false
  autoApplyDowns = false
}
```
# plugins.sbt
```
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.12")
```
# build.sbt
```
name := "play-scala"

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.8"

libraryDependencies ++= Seq(
  cache,
  ws,

  "com.typesafe.play" %% "play-slick-evolutions" % "2.0.2",
  "com.h2database" % "h2" % "1.4.193"
)
```

the page with title `Database 'default' needs evolution!` shows again and again after click on `Apply script` button.

When use play-slick-evolutions:2.0.2 then uses: 
```
com.typesafe.play:play-jdbc-api_2.11:2.5.0:jar
com.typesafe.play:play-jdbc-evolutions_2.11:2.5.0:jar
```

When use play 2.5.4 evaluations work correctly.
When use `play.evolutions.autoApply = true` evaluations work correctly.
When use only jdbc without slick evaluations work correctly.

# 1.sql
```
# --- !Ups
CREATE TABLE "employee"("id" SERIAL PRIMARY KEY ,"name" varchar(200) , "email" varchar(200)  ,"company_name" varchar,"position" varchar);
INSERT INTO "employee" values (1,'Vikas', 'vikas@knoldus.com','Knoldus','CTO');
INSERT INTO "employee" values (2,'Bhavya', 'bhavya@knoldus.com','Knoldus','Senior Director');
INSERT INTO "employee" values (3,'Ayush', 'ayush@knoldus.com','Knoldus','Lead Consultant');
INSERT INTO "employee" values (4,'Satendra', 'satendra@knoldus.com','Knoldus','Senior Consultant');

# --- !Downs
DROP TABLE "employee";
```

**Comment by marcospereira** [comment]
Hey @emsoft,

Could you create a small project that reproduces this problem? Also, does this happens only when using H2 in memory or with other databases too? Is there a stack trace or other errors?

**Comment by emsoft** [comment]
I used only H2 in memory.
Test project: https://github.com/emsoft/activator-play-slick-app.git
Steps:
1. $ git clone https://github.com/emsoft/activator-play-slick-app.git
2. $ cd activator-play-slick-app
3. $ ./activator run

**Comment by marcospereira** [comment]
Hum, this is probably related to the fact that when using H2 in-memory, all the data is lost when closing all the connections to the database. From [H2 docs](http://www.h2database.com/html/features.html#in_memory_databases):

> By default, closing the last connection to a database closes the database. For an in-memory database, this means the content is lost. To keep the database open, add ;DB_CLOSE_DELAY=-1 to the database URL. To keep the content of an in-memory database as long as the virtual machine is alive, use jdbc:h2:mem:test;DB_CLOSE_DELAY=-1

If I remember correctly, we fixed an issue where the connection pool was not properly closed when restarting the application. This could also be related to some H2 update.

@emsoft could you please test with `;DB_CLOSE_DELAY=-1`?

Thanks.

**Comment by emsoft** [comment]
Yes, it's work fine!
Most likely you've fixed it in play 2.5.5.
Thank you!

**Comment by marcospereira** [comment]
By the way, this was already documented here:

https://www.playframework.com/documentation/2.5.x/Developing-with-the-H2-Database#Prevent-in-memory-DB-reset

I've found it while revising the docs to see if this information was already available somewhere. :-)

**Comment by emsoft** [comment]
Yes, Play has good documentation!
Thanks.
