### ISSUE TITLE
Using JDBCProfile with HasDatabaseConfig

### ISSUE THREAD

**Issue by apatzer** [playframework/play-slick#401]
In Slick 3.1.x, one of the suggested methods for dependency injection was:

```
trait DAOSlick extends DBTableDefinitions with HasDatabaseConfigProvider[JdbcProfile]

class MyDAO @Inject()(protected val dbConfigProvider: DatabaseConfigProvider) extends DAOSlick { 
  import api._
  def findSomething(id: Long) { db.run(Widgets.filter(_.id === id).result) }
 }
```

This is still suggested on https://www.playframework.com/documentation/2.6.x/PlaySlick#databaseconfig-via-runtime-dependency-injection

Unfortunately with the 3.1 => 3.2 refactor of 'slick.driver' to 'slick.profile' we now get a conflict:

```
overriding value profile in trait JdbcProfile of type slick.jdbc.JdbcProfile;
lazy value profile in trait HasDatabaseConfig of type slick.jdbc.JdbcProfile has weaker access privileges; it should be public
```

This seems to stem from https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/jdbc/JdbcProfile.scala#L19 (which was only added in Slick 3.2.0) being in conflict with https://github.com/playframework/play-slick/blob/master/src/core/src/main/scala/play/api/db/slick/DatabaseConfigProvider.scala#L155

Anyone seen this and have a good resolution for how to mix `trait HasDatabaseConfigProvider[JdbcProfile]` into a DAO?

**Comment by apatzer** [comment]
Looks like the issue was my DBTableDefinitions extending the a [PostgresProfile](https://github.com/tminglei/slick-pg/blob/master/core/src/main/scala/com/github/tminglei/slickpg/ExPostgresProfile.scala) which in turn extended a JdbcProfile. The ordering of this inheritance caused the weaker access privileges error.

**Comment by mrwillis** [comment]
I'm using slick code-gen and I'm having this issue. I'm mixing in the `Tables` as well as `HasDatabaseConfigProvider[PostgresProfile]` into my service/DAO classes. Is there any way to get this to play nicely with play-slick?

Here is my code:

```scala
class ExchangeSettingService @Inject()(
    @NamedDatabase("cikauser") protected val dbConfigProvider: DatabaseConfigProvider,
    implicit val ec: ExecutionContext)
    extends HasDatabaseConfigProvider[MyPostgresProfile]
    with Tables {
   
    import dbConfig.profile.api._
}
```
