### ISSUE TITLE
Insert into Postgresql type bigint as bytea being null

### ISSUE THREAD

**Issue by berk-can** [playframework/play-slick#431]
I am using Slick for Lagom service to persist events into Postgres,
There is a field of type BIGINT, but the field that needs to be stored is null in insert command,
Slick fails to insert null into bigint field, throws exception as shown below:

`throws exception: org.postgresql.util.PSQLException: ERROR: column "sequence_offset" is of type bigint but expression is of type bytea`

is there a way to fix this?

(PS:I can manually insert into my table as that field being null with no problem)

**Comment by TimMoore** [comment]
I think this issue might have been created in the wrong place. Lagom does not use play-slick.

**Comment by berk-can** [comment]
Opened issue under Slick with link https://github.com/slick/slick/issues/1869
