### ISSUE TITLE
play 2.7 docs mention play-slick 3.0.0

### ISSUE THREAD

**Issue by pjfanning** [playframework/play-slick#460]
https://www.playframework.com/documentation/2.7.x/PlaySlick

Is play-slick 4.0.0 and slick 3.3.0 required for play 2.7.0? Or does play-slick 3.0.x would ok with play 2.7.0?

**Comment by marcospereira** [comment]
Yep, 

We need to update the docs here: https://github.com/playframework/play-slick/tree/master/docs/manual/working/scalaGuide/main/sql/slick

Thanks for noticing this, @pjfanning. Do you want to submit a PR to fix this issue?

**Comment by renatocaval** [comment]
Fixed on #461
