### ISSUE TITLE
Restart connection pools when DB credentials expire

### ISSUE THREAD

**Issue by amarouni** [playframework/play-slick#472]
Hi,

Play Version : 2.6.6 / Play Slick : 3.0.0 / Slick : 3.2.3

I'm working on an app with a particular setup where DB credentials change overtime. The `username`/`password` can change at any instant which with the current code/config causes the app to fail (expected).

My question is the following : what is the best way to manage this particular setup ? Is there any possible way to restart the connection pool with the new credentials when they get rotated without restarting the app ? Any HikariCP config to force pool restart when the connections cannot be created ?

Thanks,

**Comment by renatocaval** [comment]
I'm not aware of any of this. Ideally, this should be something indeed at the level of HikariCP. Have you asked on their Gitter/mailing list?

 We will probably need some change in play-slick to support this. Alternatively you can hack your own solution. Having some facade between your code and Slick Database instance and swap them when the credentials expire.

**Comment by amarouni** [comment]
Thanks @renatocaval I asked the same question on HikariCP : https://github.com/brettwooldridge/HikariCP/issues/1363. I'll report back here.
