### ISSUE TITLE
Bump Play version to 2.7.1

### ISSUE THREAD

**Issue by PawelLipski** [playframework/play-slick#473]
Currently the latest version of play-slick depends on Play 2.7.0. When a project uses Play 2.7.1 and play-slick 4.0.0, many SBT evictions occur (on Play itself and its transitive dependencies). Providing a version of play-slick that depends on Play 2.7.1 would help keep dependencies of both in sync.

**Comment by marcospereira** [comment]
Fixed by https://github.com/playframework/play-slick/pull/483, where Play was updated to 2.7.3.
