### ISSUE TITLE
make documentation on DDL clearer

### ISSUE THREAD

**Issue by freekh** [playframework/play-slick#55]
Currently, the doc is not explicit about the benefits of DDL creation. Should also specify in which uses cases you should not use DDL creation.

**Comment by Ciantic** [comment]
Yes! Documentation is fuzzy. Right now I don't even know how can I make play-slick to generate table schema (I don't want to write CREATE TABLE statements during development all the time as they change)

**Comment by dotta** [comment]
> Yes! Documentation is fuzzy. 

@Ciantic DDL creation was removed. See https://www.playframework.com/documentation/2.4.x/PlaySlickMigrationGuide#DDL-support-was-removed. I think the documentation is clear that DDL generation is no longer supported. Therefore, you'll have to maintain your database schema using tools such as Play evolutions (which is supported in play-slick), [play-liquibase](https://github.com/Ticketfly/play-liquibase) or some other tool.

**Comment by dotta** [comment]
I'm closing this ticket as it's no longer actual.
