### ISSUE TITLE
please release new version

### ISSUE THREAD

**Issue by xuwei-k** [playframework/play-slick#695]
Because can't use slick 3.4.1 and play-slick 5.0.2 without `libraryDependencySchemes` or `evictionErrorLevel` setting because [slick `versionSchemes` is `pvp`](https://github.com/slick/slick/blob/c2c76972b1a3924c3f0e180f8f9e32698f3f94e3/build.sbt#L102).

```
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error] 	* com.typesafe.slick:slick_2.12:3.4.1 (pvp) is selected over 3.3.2
[error] 	    +- com.typesafe.slick:slick-hikaricp_2.12:3.4.1       (depends on 3.4.1)
[error] 	    +- com.typesafe.play:play-slick_2.12:5.0.2            (depends on 3.3.2)
```

_Originally posted by @xuwei-k in https://github.com/playframework/play-slick/issues/693#issuecomment-1251816531_

**Comment by mkurz** [comment]
@xuwei-k I can release a new version. What do you think about making it version 5.1?

**Comment by xuwei-k** [comment]
> What do you think about making it version 5.1?

LGTM 👍

**Comment by mkurz** [comment]
Done: https://github.com/playframework/play-slick/releases/tag/5.1.0

**Comment by xuwei-k** [comment]
Thanks! 👍

**Comment by mkurz** [comment]
You are welcome. Please test the release and let me know if everything works.
