### ISSUE TITLE
6.0.0 Release?

### ISSUE THREAD

**Issue by cheeseng** [playframework/play-slick#802]
It seems like for Play Framework 3.0.0 we need play-slick 6.0.0 as mentioned in its documentation: 

https://www.playframework.com/documentation/3.0.x/PlaySlick

But currently it seems like only 6.0.0-M2 is available, may I know when 6.0.0 final willl be available?

Thanks.

**Comment by mkurz** [comment]
The reason for that is that slick only has a 3.5.0-M4 release yet, no final 3.5.0 yet...  There are still things missing for slick, I was pinging them last week:
* https://github.com/slick/slick/discussions/2759#discussioncomment-7401898

That's why we did not publish play-slick 6.0.0 yet...

**Comment by cheeseng** [comment]
@mkurz Oh I see, bummer, seems like we still need more patience.  :)

**Comment by marko-asplund** [comment]
We're in the same situation.
What's the value you see from Slick v3.5 for Play Slick users?
I'd argue, however, that Slick v3.5 would bring little to no value to most users of Play Slick, and that releasing with Play 3.0 would be of huge value.
My suggestion is to downgrade Slick and release Play Slick ASAP.
Here's a PR: https://github.com/playframework/play-slick/pull/803
Thank you! 😄

**Comment by marko-asplund** [comment]
Slick 3.5. release cycle started on 2023-01-12, so judging from the cycle length so far, it may be difficult to estimate when the release will actually happen.

**Comment by mkurz** [comment]
Hmm. yes probably makes sense to just use slick 3.4 now so people can at least upgrade to Play 2.9+. However they will not get Scala 3 support for now. But anyway, we can cut another release as soon as slick 3.5 stable is out.

**Comment by mkurz** [comment]
6.0.0 and 5.2.0 released now, however staying on slick 3.4 for now, which means we do not ship support for Scala 3 yet: 
- https://github.com/playframework/play-slick/releases/tag/6.0.0 supporting Play 3.0
- https://github.com/playframework/play-slick/releases/tag/5.2.0 supporting Play 2.9

As soon as slick 3.5 is out, we will release 6.1 and 5.3:
- #805
- #806

**Comment by marko-asplund** [comment]
This is awesome! 🎉 
Thank you so much @mkurz ! 🙇
