### ISSUE TITLE
Need to refactor DBAction

### ISSUE THREAD

**Issue by loicdescotte** [playframework/play-slick#81]
Several problems need to be fixed around DBAction : 

1) Use `SimpleResult` and `Action.async`  to avoid Play 2.2 warnings 

``` shell
[warn] play-slick/src/main/scala/play/api/db/slick/package.scala:42: trait Result in package mvc is deprecated: Result will become SimpleResult in Play 2.3
[warn]     def apply(r: (RequestWithDbSession) => Result)(implicit app:Application) = {
[warn]                                         ^
[warn] play-slick/src/main/scala/play/api/db/slick/package.scala:44: class AsyncResult in package mvc is deprecated: Use Future[SimpleResult] with Action.async action builder instead. Will be removed in Play 2.3.
[warn]         AsyncResult {
```

2) Future should wrap all the action/session : http://stackoverflow.com/questions/18579684/play-slick-and-async-is-it-a-race-condition

3) DBAction should be able to take a database name parameter (see https://github.com/freekh/play-slick/issues/78)

**Comment by PhilAndrew** [comment]
How can I use DBAction with SecuredAction ?
