### ISSUE TITLE
Body parsers and ActionBuilder

### ISSUE THREAD

**Issue by jmparsons** [playframework/play-slick#84]
I don't know if this is already on the roadmap, but if DBAction extended ActionBuilder to take in body parsers and have async would be really nice. 

I have a play-slick example app using backbone and json calls, so my crud uses body parsers to validate against.

https://github.com/jmparsons/play-scala-backbone-todo

`DBAction(parser.json)` etc.

**Comment by slorber** [comment]
+1 using an action builder would make action composition more easier.
I need a composition of DBAction and UserAuthenticatedAction for exemple

**Comment by dotta** [comment]
Since play-slick 1.0.0 is using stock Play 2.4, the problem reported in this ticket is no longer actual.

**Comment by dotta** [comment]
Here are some additional information about the removal of `DbAction` https://www.playframework.com/documentation/2.4.x/PlaySlickMigrationGuide#DBAction-and-DBSessionRequest-were-removed
