### ISSUE TITLE
Functional Test Friendly : Operate without a running play application

### ISSUE THREAD

**Issue by diwa** [playframework/play-slick#87]
It would be great to run the functional tests for the controller (and layers below) without having to start a play application (similar to the approach of 42eng - http://eng.42go.com/speed-up-play-tests-direct/, 
http://eng.42go.com/scala-slick-database-drivers-type-safing-session-concurrency/,
http://eng.42go.com/using-scala-slick-at-fortytwo/)

#### Database Object
For the `Database` object, the implicit app dependency is only to extract the configuration for building the data source.

It will be great if this can be refactored for ex. by introducing a trait `DBSourceProvider`

    trait DBSourceProvider {
      def datasource: javax.sql.DataSource
      def driverName: String
    }

    object Database {
     def apply(name: String = "default")(implicit dbSourceProvider: DBSourceProvider) = new Database(name, dbSourceProvider)
    }
and having `AppDBSourceProvider`, `InMemoryDBSourceProvider` etc. while retaining the current interface as well.

#### DBAction
For `DBAction`, there are several approaches possible at the application level once the `app` dependency of the `Database` object is removed. If a composable actionbuilder version is created, we could create a wrapper action which uses a different underlying action for test mode (without app and execution context).
Another approach is to inject the action to be used via DI (like Guice). 

**WDYT?**

**Comment by dotta** [comment]
Indeed. Using Play 2.4 and DI, together with play-slick 1.0.0 should solve all issues :-)
